spring:
  profiles.active: it
  jpa.properties.hibernate.generate_statistics: true
  datasource.hikari.pool-name: hikari-connection-pool
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
  liquibase: #https://javadeveloperzone.com/spring-boot/spring-boot-liquibase-example/
    enabled: true
    contexts: prod, qa
    liquibase-schema: liquibase
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:/db-changelog.xml
    rollback-file: liquibase-rollback.sql

---

spring:
  config.activate.on-profile: ut
  main.lazy-initialization: true
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

---

spring:
  config.activate.on-profile: it
  main.lazy-initialization: true
  datasource:
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:memory:dbo-db;create=true
    username: APP
    password: APP
    hikari:
      maximumPoolSize: 2
      minimumIdle: 1

---

spring:
  config.activate.on-profile: st
  datasource:
    driverClassName: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 1800000
  liquibase:
    test-rollback-on-update: true
